### ISSUE TITLE
make SimpleFixture.Moq target .netstandard1.3

### ISSUE THREAD

**Issue by powerdude** [ipjohnson/SimpleFixture#19]
Hello,

Is there any chance you can make this target 1.3 like Moq does instead of 1.6?

thanks

cliff

**Comment by ipjohnson** [comment]
Hi Cliff,

That should be easy enough, I'll make the change this evening and do a release.

-Ian

**Comment by ipjohnson** [comment]
I've released a new version re-targeting to standard 1.3

**Comment by powerdude** [comment]
that's awesome.  thanks.
