### ISSUE TITLE
Change references to NETStandard.Library 1.6.0

### ISSUE THREAD

**Issue by ipjohnson** [ipjohnson/SimpleFixture#28]
To simplify the dependencies for the package NETStandard.Library 1.6.0 will be used instead of picking and choosing the dependencies for the .netstandard 1.0 target

**Comment by powerdude** [comment]
it'd be better to use 1.4 or something.  I use this for a xamarin project and 1.4 supports ios, android and uwp.

**Comment by ipjohnson** [comment]
Simplefixture targets .net45 and netstandard 1.0. 

This change didn't  really change much as I had originally chosen a subset of the packages that comprise NETStandard.Library 1.6.0, now it's just dependent on all of them.

https://www.nuget.org/packages/NETStandard.Library/1.6.0

I've not tried ios and andriod but as part of 3.0.0 I added support for SimpleFixture.MSTest which supports UWP (I was testing it yesterday in fact).
