### ISSUE TITLE
Support for DateTimeOffset

### ISSUE THREAD

**Issue by sorvis** [ipjohnson/SimpleFixture#37]
It seems like Fixture does not support creating data for DateTimeOffset. Would it be possible to add support?

[C# Fiddle Example](https://dotnetfiddle.net/RvZcIM)
```
using System;
using SimpleFixture;
					
public class Program
{
	public static void Main()
	{
		
		var fixture = new Fixture();
		var modelInstance = fixture.Generate<TestModel>();
	}
}

public class TestModel{
	public DateTimeOffset StartDate { get; set; }
}
```

**Comment by ipjohnson** [comment]
I agree it should work out of the box.

**Comment by ipjohnson** [comment]
I've released a new version with support for DateTimeOffset.
